# Generated by Django 2.0.6 on 2018-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='', max_length=500)),
                ('título', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, upload_to='../media/cupom_system/media')),
                ('imagem_de_capa', models.ImageField(blank=True, upload_to='../media/cupom_system/media')),
                ('quantidade', models.IntegerField(default=0, null=True)),
                ('preço_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preço_promocional', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horário_de_consumo', models.CharField(default='', max_length=500)),
                ('status', models.CharField(choices=[('Ativada', 'Ativo'), ('Inativa', 'Inativo'), ('Cancelada', 'Cancelado'), ('Expirada', 'Expirado')], max_length=500)),
                ('regras_gerais', models.TextField(default='', max_length=3000)),
                ('descrição', models.TextField(default='', max_length=3000)),
            ],
        ),
    ]
