# Generated by Django 2.0.6 on 2018-06-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='imagem_de_capa',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='thumbnail',
        ),
    ]
