# Generated by Django 2.0.6 on 2018-06-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom_sys', '0002_auto_20180630_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='categoria',
        ),
    ]
